
package sh.luka.fractal.wsclient;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FractalWSImpl", targetNamespace = "http://ws.fractal.luka.sh/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FractalWSImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSessionID", targetNamespace = "http://ws.fractal.luka.sh/", className = "sh.luka.fractal.wsclient.GetSessionID")
    @ResponseWrapper(localName = "getSessionIDResponse", targetNamespace = "http://ws.fractal.luka.sh/", className = "sh.luka.fractal.wsclient.GetSessionIDResponse")
    @Action(input = "http://ws.fractal.luka.sh/FractalWSImpl/getSessionIDRequest", output = "http://ws.fractal.luka.sh/FractalWSImpl/getSessionIDResponse")
    public int getSessionID(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFractal", targetNamespace = "http://ws.fractal.luka.sh/", className = "sh.luka.fractal.wsclient.GetFractal")
    @ResponseWrapper(localName = "getFractalResponse", targetNamespace = "http://ws.fractal.luka.sh/", className = "sh.luka.fractal.wsclient.GetFractalResponse")
    @Action(input = "http://ws.fractal.luka.sh/FractalWSImpl/getFractalRequest", output = "http://ws.fractal.luka.sh/FractalWSImpl/getFractalResponse")
    public String getFractal(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFractalFileName", targetNamespace = "http://ws.fractal.luka.sh/", className = "sh.luka.fractal.wsclient.GetFractalFileName")
    @ResponseWrapper(localName = "getFractalFileNameResponse", targetNamespace = "http://ws.fractal.luka.sh/", className = "sh.luka.fractal.wsclient.GetFractalFileNameResponse")
    @Action(input = "http://ws.fractal.luka.sh/FractalWSImpl/getFractalFileNameRequest", output = "http://ws.fractal.luka.sh/FractalWSImpl/getFractalFileNameResponse")
    public String getFractalFileName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Double>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getScale", targetNamespace = "http://ws.fractal.luka.sh/", className = "sh.luka.fractal.wsclient.GetScale")
    @ResponseWrapper(localName = "getScaleResponse", targetNamespace = "http://ws.fractal.luka.sh/", className = "sh.luka.fractal.wsclient.GetScaleResponse")
    @Action(input = "http://ws.fractal.luka.sh/FractalWSImpl/getScaleRequest", output = "http://ws.fractal.luka.sh/FractalWSImpl/getScaleResponse")
    public List<Double> getScale(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Integer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getIterationNumbers", targetNamespace = "http://ws.fractal.luka.sh/", className = "sh.luka.fractal.wsclient.GetIterationNumbers")
    @ResponseWrapper(localName = "getIterationNumbersResponse", targetNamespace = "http://ws.fractal.luka.sh/", className = "sh.luka.fractal.wsclient.GetIterationNumbersResponse")
    @Action(input = "http://ws.fractal.luka.sh/FractalWSImpl/getIterationNumbersRequest", output = "http://ws.fractal.luka.sh/FractalWSImpl/getIterationNumbersResponse")
    public List<Integer> getIterationNumbers(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCurrentIteration", targetNamespace = "http://ws.fractal.luka.sh/", className = "sh.luka.fractal.wsclient.GetCurrentIteration")
    @ResponseWrapper(localName = "getCurrentIterationResponse", targetNamespace = "http://ws.fractal.luka.sh/", className = "sh.luka.fractal.wsclient.GetCurrentIterationResponse")
    @Action(input = "http://ws.fractal.luka.sh/FractalWSImpl/getCurrentIterationRequest", output = "http://ws.fractal.luka.sh/FractalWSImpl/getCurrentIterationResponse")
    public int getCurrentIteration(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "uploadImage", targetNamespace = "http://ws.fractal.luka.sh/", className = "sh.luka.fractal.wsclient.UploadImage")
    @ResponseWrapper(localName = "uploadImageResponse", targetNamespace = "http://ws.fractal.luka.sh/", className = "sh.luka.fractal.wsclient.UploadImageResponse")
    @Action(input = "http://ws.fractal.luka.sh/FractalWSImpl/uploadImageRequest", output = "http://ws.fractal.luka.sh/FractalWSImpl/uploadImageResponse")
    public boolean uploadImage(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        byte[] arg1);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "finishSuccessIteration", targetNamespace = "http://ws.fractal.luka.sh/", className = "sh.luka.fractal.wsclient.FinishSuccessIteration")
    @ResponseWrapper(localName = "finishSuccessIterationResponse", targetNamespace = "http://ws.fractal.luka.sh/", className = "sh.luka.fractal.wsclient.FinishSuccessIterationResponse")
    @Action(input = "http://ws.fractal.luka.sh/FractalWSImpl/finishSuccessIterationRequest", output = "http://ws.fractal.luka.sh/FractalWSImpl/finishSuccessIterationResponse")
    public void finishSuccessIteration(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
